name: Automatic Pull Request

on:
  push:
    branches-ignore:
      - master


jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - run: gh pr create --fill --fill-verbose
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
